### ISSUE TITLE
how to use the type array enum for python？ 

### ISSUE THREAD

**Issue by Tysonliang** [eProsima/Fast-DDS-python#44] opened 2022-09-02 08:15 UTC
for the C++: 
 i define the idle:
  enum D { A, B}
 struct Test{ double C, D d[2], double E[2]}
while i use the topic like fllow:
   test = Test()
   test.d()[0]
it is erro.
But i use the topic like fllow:
   test = Test()
   test.E()[0]
it is ok.

**Comment by Tysonliang** [comment] 2023-02-02 12:21
any response?

**Comment by richiware** [comment] 2023-10-06 07:59
Pull request #66 should fix the problem with collection of enumerations.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-10-25 06:12
Closing the issue as the fix has already been merged. Feel free to reopen if the issue is still happening after upgrading.

**Closed by JLBuenoLopez-eProsima** 2023-10-25 06:12 UTC
